# Generated by Django 5.2 on 2025-09-29 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socity_officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('socity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.socity')),
            ],
        ),
    ]
