# Generated by Django 5.2 on 2025-09-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_socity_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='socity_officer',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='socity_officer',
            name='img',
            field=models.ImageField(upload_to='officers/'),
        ),
    ]
