# Generated by Django 5.2 on 2025-09-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_socity_officer_position_alter_socity_officer_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='socity',
            name='header',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='socity',
            name='img',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='posts/'),
        ),
    ]
