# Generated by Django 5.2 on 2025-09-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_socity_header_socity_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_officers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('Position', models.CharField()),
                ('img', models.CharField()),
            ],
        ),
    ]
