# Generated by Django 5.2 on 2025-09-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_branch_officers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch_officers',
            new_name='branch_officer',
        ),
    ]
