# Generated by Django 5.2 on 2025-09-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_branch_officers_branch_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_officer',
            name='img',
            field=models.ImageField(upload_to='officers/'),
        ),
    ]
