# Generated by Django 5.2 on 2025-09-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_branch_officer_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_officer',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='branch_officer',
            name='Position',
            field=models.CharField(max_length=100),
        ),
    ]
