# Generated by Django 5.2 on 2025-09-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_branch_officer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_officer',
            name='Linkedin',
            field=models.URLField(default='https://www.linkedin.com/feed/'),
        ),
    ]
