# Generated by Django 5.2 on 2025-09-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_branch_officer_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_officer',
            name='Posting_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
