# Generated by Django 5.2 on 2025-09-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_branch_officer_posting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch_officer',
            name='Posting_Date',
        ),
        migrations.AddField(
            model_name='post',
            name='Posting_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
