# Generated by Django 5.2 on 2025-09-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_branch_officer_posting_date_post_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Posting_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
